import os
import requests
import json
import time

class FeishuUploader:
    def __init__(self, app_id, app_secret):
        self.app_id = app_id
        self.app_secret = app_secret
        self.token = None
        self.token_expiry = 0

    def get_tenant_access_token(self):
        if self.token and time.time() < self.token_expiry:
            return self.token

        url = "https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal"
        headers = {"Content-Type": "application/json; charset=utf-8"}
        data = {
            "app_id": self.app_id,
            "app_secret": self.app_secret
        }
        
        try:
            response = requests.post(url, headers=headers, json=data)
            response.raise_for_status()
            res_json = response.json()
            if res_json.get("code") == 0:
                self.token = res_json.get("tenant_access_token")
                # Expire 5 minutes early to be safe
                self.token_expiry = time.time() + res_json.get("expire", 7200) - 300
                return self.token
            else:
                raise Exception(f"Failed to get access token: {res_json}")
        except Exception as e:
            print(f"Error getting tenant_access_token: {e}")
            raise

    def get_folder_token(self, folder_name=None):
        # Placeholder: ideally search for folder by name or return root
        # For now, if no folder token is provided by user, we might need to create one or use root.
        # But usually uploading to root requires the root folder token. 
        # For now, return None, hoping the API defaults to root or user provides a specific token.
        return None 

    def upload_file(self, file_path, parent_folder_token=""):
        if not os.path.exists(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")

        file_size = os.path.getsize(file_path)
        file_name = os.path.basename(file_path)
        token = self.get_tenant_access_token()

        # Simple threshold: 20MB
        if file_size < 20 * 1024 * 1024:
            return self._upload_small_file(file_path, file_name, file_size, parent_folder_token)
        else:
            return self._upload_large_file(file_path, file_name, file_size, parent_folder_token)

    def _upload_small_file(self, file_path, file_name, file_size, parent_folder_token):
        url = "https://open.feishu.cn/open-apis/drive/v1/files/upload_all"
        headers = {"Authorization": f"Bearer {self.token}"}
        
        # multipart/form-data
        with open(file_path, 'rb') as f:
            files = {'file': (file_name, f)}
            data = {
                'file_name': file_name,
                'parent_type': 'explorer',
                'parent_node': parent_folder_token,
                'size': str(file_size)
            }
            response = requests.post(url, headers=headers, files=files, data=data)
            return response.json()

    def _upload_large_file(self, file_path, file_name, file_size, parent_folder_token):
        # 1. Prepare
        url_prepare = "https://open.feishu.cn/open-apis/drive/v1/files/upload_prepare"
        headers = {"Authorization": f"Bearer {self.token}", "Content-Type": "application/json"}
        data_prepare = {
            "file_name": file_name,
            "parent_type": "explorer",
            "parent_node": parent_folder_token,
            "size": file_size
        }
        res_prepare = requests.post(url_prepare, headers=headers, json=data_prepare).json()
        if res_prepare.get("code") != 0:
            raise Exception(f"Upload prepare failed: {res_prepare}")
        
        upload_id = res_prepare["data"]["upload_id"]
        block_size = res_prepare["data"]["block_size"]
        blocks = res_prepare["data"]["block_num"]
        
        # 2. Upload parts
        with open(file_path, 'rb') as f:
            for i in range(blocks):
                chunk = f.read(block_size)
                url_part = "https://open.feishu.cn/open-apis/drive/v1/files/upload_part"
                # multipart/form-data for part
                files = {'file': (file_name, chunk)}
                data_part = {
                    'upload_id': upload_id,
                    'seq': i,
                    'size': len(chunk)
                }
                # headers for multipart are auto-generated by requests if not set (or if specific auth header set)
                # But here we need Authorization header
                headers_part = {"Authorization": f"Bearer {self.token}"} 
                
                res_part = requests.post(url_part, headers=headers_part, files=files, data=data_part).json()
                if res_part.get("code") != 0:
                    raise Exception(f"Upload part {i} failed: {res_part}")
                print(f"Uploaded part {i+1}/{blocks}")

        # 3. Finish
        url_finish = "https://open.feishu.cn/open-apis/drive/v1/files/upload_finish"
        data_finish = {
            "upload_id": upload_id,
            "block_num": blocks
        }
        # re-use json header
        res_finish = requests.post(url_finish, headers=headers, json=data_finish).json()
        if res_finish.get("code") != 0:
            raise Exception(f"Upload finish failed: {res_finish}")
        
        return res_finish
